blog: Add IPFS experiment post
haiku/website pull request #497
Opened 2021-05-08 14:01 UTC by kallisti5

2021-06-07 22:20 UTC, jt15s commented
Any progress on this?

2021-06-08 02:23 UTC, kallisti5 commented
nope, i've been distracted :)

I'm still continuously mirroring haiku / repos / release images to ```/ipns/hpkg.haiku-os.org```

I'll try and finish this post up

2021-06-16 20:18 UTC, kallisti5 commented
Updated some of the language based on some of @nielx 's feedback.  Tried to make the language a little more common and less tech.

I think the article is a little long?  Might need trimmed down a bit.

2021-06-21 22:31 UTC, jt15s commented
Is this ready to merge?

2021-07-10 19:21 UTC, leavengood requested changes

2021-07-10 19:21 UTC, leavengood commented on content/blog/kallisti5/2021-05-03_ipfs_experiment.md
> +In ~2018 I moved our Haiku package repositories (and nightly images, and release images) to S3 object storage. This helped to reduce the large amount of data we were lugging around on our core infras
```suggestion
Around 2018 I moved our Haiku package repositories (and nightly images, and release images) to S3 object storage. This helped to reduce the large amount of data we were lugging around on our core infrastructure, and offloaded it onto an externally managed service which we could programmatically manage. All of our CI/CD could securely and programmatically build artifacts into these S3 buckets. We found a great vendor which let us host a lot of data with unlimited egress (outbound) bandwidth for an amazing price. This worked great through 2021, however the vendor recently began walking back their "unlimited egress bandwidth" position.  In late April 2021, they shutdown our buckets resulting in a repo + nightly outage of ~24 hours while we negotiated with their support team.
```

2021-07-10 19:21 UTC, leavengood commented on content/blog/kallisti5/2021-05-03_ipfs_experiment.md
> +* Haiku's go-lang port needs a lot more work before we can build IPFS on Haiku.
```suggestion
* Haiku's Golang port needs a lot more work before we can build IPFS on Haiku.
```

2021-07-10 19:21 UTC, leavengood commented on content/blog/kallisti5/2021-05-03_ipfs_experiment.md
> +A few users have mentioned adding native IPFS support to pkgman.. this would enable Haiku to obtain updates
```suggestion
A few users have mentioned adding native IPFS support to pkgman...this would enable Haiku to obtain updates
```

2021-07-10 19:22 UTC, leavengood commented
Let's stop holding up blog posts over minor things. I don't think this is too long. I fixed a few issues in this one with my suggestions above. If I don't hear any feedback in a few hours I will apply those and merge.

2021-09-07 09:05 UTC, korli commented
> Let's stop holding up blog posts over minor things. I don't think this is too long. I fixed a few issues in this one with my suggestions above. If I don't hear any feedback in a few hours I will apply those and merge.

I think there is no feedfack ...  ping :)

2021-09-07 13:14 UTC, kallisti5 commented
Honestly... i'm fizzling out a bit on this.

While the idea is sound (and I used IPFS for the distribution of R1/Beta3), in actual practice at scale IPFS sucks for "big data sets".   Getting huge amounts of data pinned is unclear and unreliable from the perspective of the person trying to mirror the data.

Being able to let users "simply pin + seed our package repos to users" was really appealing.. but given the issues above it's a bit less appealing.

**Some example issues:**

* https://github.com/ipfs/go-ipfs/issues/8103
* https://github.com/ipfs/go-ipfs/issues/7586
* https://github.com/ipfs/go-ipfs/issues/3066#issuecomment-833006651
* https://github.com/ipfs/go-ipfs/issues/1702#issuecomment-670977139

I'm still mirroring our package repositories on IPFS, but not sure how hard we should push it.

tldr; The *idea* is awesome and looks like something we *badly* need.  The execution is a bit less awesome.

2021-12-16 00:20 UTC, jt15s commented
`tldr; The idea is awesome and looks like something we badly need. The execution is a bit less awesome.`

I guess we can probably note the shortcomings of IPFS in the blog post then - it's an experiment so there are bound to be things that need improving.

2024-09-13 15:28 UTC, closed without merging