Create new blog post about WebPositive
haiku/website pull request #548
Opened 2021-08-10 23:37 UTC by jt15s

Added new blog post on behalf of animortis, talking about Web+

2021-08-11 00:12 UTC, kallisti5 commented
@pulkomandy should really review this one :-)

2021-08-11 00:13 UTC, kallisti5 commented on content/blog/animortis/2021-08-10_positively_critical_webpositive_and_haiku.md
> +WebPositive wasn’t the only browser for Haiku. But with the additional portability and power of the WebKit1 engine as it existed at the time, the team decided to build it into  WebPositive and make i
grammar. Starting a sentence with "But"

2021-08-11 00:15 UTC, leavengood requested changes
Very nice article. I just wanted to correct the spelling of Maxime's name, and also decided to add stippi's full name, though later there is a big list of nicknames,

2021-08-11 00:15 UTC, leavengood commented on content/blog/animortis/2021-08-10_positively_critical_webpositive_and_haiku.md
> +Haiku developer Ryan Leavengood started efforts to port the engine to create WebPositive in 2008. In 2009, WebPositive won a slot as part of the Google Summer of Code, and student developer Maxine Si
```suggestion
Haiku developer Ryan Leavengood started efforts to port the engine to create WebPositive in 2008. In 2009, WebPositive won a slot as part of the Google Summer of Code, and student developer Maxime Simon was able to get the browser in a “mostly usable” state while developer Stephan Aßmus (stippi) built the browser framework itself.   
```

2021-08-11 00:33 UTC, jt15s commented on content/blog/animortis/2021-08-10_positively_critical_webpositive_and_haiku.md
> +WebPositive wasn’t the only browser for Haiku. But with the additional portability and power of the WebKit1 engine as it existed at the time, the team decided to build it into  WebPositive and make i
@kallisti5 Fixed!

2021-08-11 05:14 UTC, korli commented on content/blog/animortis/2021-08-10_positively_critical_webpositive_and_haiku.md
> +WebPositive wasn’t the only browser for Haiku, but with the additional portability and power of the WebKit1 engine as it existed at the time, the team decided to build it into  WebPositive and make i
```suggestion
WebPositive wasn’t the only browser for Haiku, but with the additional portability and power of the WebKit1 engine as it existed at the time, the team decided to build it into WebPositive and make it the official browser for the OS.
```

2021-08-11 06:33 UTC, pulkomandy commented
> @pulkomandy should really review this one :-)

I have already reviewed it privately after being interviewed by the marketing team.

2021-08-12 15:53 UTC, aomgiwjc commented
Hey guys, anything else I can do to help move this up?

2021-08-12 18:39 UTC, kallisti5 commented
I think we need to add some call to action seeking help on Webpositive.  Help getting our patches upstream, or help on our port

2021-08-14 00:17 UTC, aomgiwjc commented
Added for the most part!

2021-08-15 01:25 UTC, jt15s commented
Does this need any more work or can it be merged?

2021-08-16 17:09 UTC, merged