blog/kallisti5: Add riscv64 blog post
haiku/website pull request #565
Opened 2021-11-07 14:51 UTC by kallisti5

2021-11-07 14:52 UTC, kallisti5 commented
Since riscv64 is now bootable in qemu as well as on the SiFive unmatched, lets advertise a little.  Maybe we'll get some more interested parties :sparkles:

2021-11-07 14:53 UTC, kallisti5 commented
do not push until the nightly images are generated.  I triggered a run here:

https://ci.haiku-os.org/teams/nightly/pipelines/master-riscv64/jobs/image-master-riscv64/builds/452

2021-11-07 16:03 UTC, pulkomandy commented
Maybe update RISC-V/qemu in https://www.haiku-os.org/guides/building/port_status to say "early functional" like the sifive unmatched?

2021-11-08 19:55 UTC, kallisti5 commented
> Maybe update RISC-V/qemu in https://www.haiku-os.org/guides/building/port_status to say "early functional" like the sifive unmatched?

Done.  


I need to adjust the instructions in this blog post as well.  The latest u-boot actually fixes the need for all of the ```pci enum; usb start; etc```

2021-11-09 05:28 UTC, korli commented on content/blog/kallisti5/2021-11-07_booting_our_risc-v_images.md
> +Overall, RISC-V offers an exciting oppertunity for us to grow our non-x86 architecture support.
```suggestion
Overall, RISC-V offers an exciting opportunity for us to grow our non-x86 architecture support.
```

2021-11-09 13:38 UTC, kallisti5 commented
Danke. Fixed.  I need to find a vim spell-check plugin.

2021-12-01 01:39 UTC, jt15s commented
@kallisti5 Any progress on this?

2021-12-01 01:43 UTC, jt15s requested changes
Just a small changed required on one of the alert boxes, I've fixed a type and added links to the relevant tickets on Trac.

2021-12-01 01:43 UTC, jt15s commented on content/blog/kallisti5/2021-11-07_booting_our_risc-v_images.md
> +{{< alert-info "Beware bugs" "There are multiple lingering bugs (#17379,#17380) in RISCV64 Haiku running under qemu. If you don't make it to the desktop, try again.">}}
```suggestion
{{< alert-info "Beware of bugs" "There are multiple lingering bugs ([#17379](https://dev.haiku-os.org/ticket/17379), [#17380](https://dev.haiku-os.org/ticket/17380)) in RISCV64 Haiku running under QEMU. If you don't make it to the desktop, try again.">}}
```

2021-12-01 19:28 UTC, kallisti5 commented
I'm just waiting for someone to +1 the change :-)

2021-12-01 19:28 UTC, merged